mybritesite/featurereq/urls.py
from django.urls import path

from . import views

app_name = 'featurereq'
urlpatterns = [
    path('', views.FeatureRequestListView.as_view(), name='index'),
    path('requests/create/', views.FeatureRequestCreateView.as_view(), name='create'),
    path('requests/update/<int:pk>/', views.FeatureRequestUpdateView.as_view(), name='update'),
    path('requests/detail/<int:pk>/', views.FeatureRequestDetailView.as_view(), name='detail'),
    path('requests/delete/<int:pk>/', views.FeatureRequestDeleteView.as_view(), name='delete'),

    #path('<int:featurerequest_id>/', views.featurerequest_detail, name='detail'),

    #path('requests/', views.featurerequest_list, name='list'),
]

mybritesite/mybritesite/urls.py
from django.contrib import admin
from django.urls import include, path
from django.views.generic import RedirectView

urlpatterns = [
    path('featurereq/', include('featurereq.urls', namespace='featurereq')),
    path('', RedirectView.as_view(pattern_name='featurereq:index', permanent=False)),
    path('admin/', admin.site.urls),
]

mybritesite/featurereq/models.py
from django.db import models

from django.utils.six import python_2_unicode_compatible
from django.urls import reverse


@python_2_unicode_compatible
class Client(models.Model):
    name = models.CharField(max_length=255, unique=True)

    class Meta:
        ordering = ('name',)

    def __str__(self):
        return self.name


@python_2_unicode_compatible
class ProductArea(models.Model):
    name = models.CharField(max_length=255)

    class Meta:
        ordering = ('name',)

    def __str__(self):
        return self.name


@python_2_unicode_compatible
class FeatureRequest(models.Model):
    title = models.CharField(max_length=255)
    description = models.TextField()
    target_date = models.DateField(null=True, blank=True)
    client = models.ForeignKey(Client, on_delete=models.PROTECT)
    client_priority = models.PositiveIntegerField(db_index=True, null=True, blank=True)
    product_area = models.ForeignKey(ProductArea, on_delete=models.PROTECT)
    ordered_field_name = 'client_priority'
    ordered_to = 'client'


    class Meta:
        ordering = ('client', 'client_priority')

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('featurereq:index')

mybritesite/featurereq/forms.py
from django import forms

from .models import FeatureRequest


class FeatureRequestForm(forms.ModelForm):

    class Meta:
        model = FeatureRequest
        fields = ['title', 'description', 'client', 'client_priority',
                  'product_area', 'target_date']
        widgets = {
            'target_date': forms.TextInput(attrs={'placeholder': 'MM/DD/YYYY'}),
        }

    def save(self, commit=True):
        priority = self.cleaned_data['client_priority']
        if FeatureRequest.objects.filter(client_priority=priority).exists():

            self.instance.client_priority = None

            # TODO move other feature requests for the client
            #self.instance.to(priority)
        else:
            self.instance.client_priority = priority
        if commit:
            self.instance.save()
        return self.instance

mybritesite/featurereq/views.py
from django.urls import reverse_lazy
from .models import Client, FeatureRequest, ProductArea
from .forms import FeatureRequestForm
from django.contrib import messages
from django.views.generic import CreateView, DeleteView, DetailView, ListView, UpdateView
from django.contrib.messages.views import SuccessMessageMixin


class FeatureRequestCreateView(CreateView):

    model = FeatureRequest
    form_class = FeatureRequestForm
    success_msg = "Feature Request created!"
    template_name = 'featurereq/featurerequest_create.html'
    success_url = reverse_lazy('featurereq:index')

    def form_valid(self, form):
        messages.info(self.request, self.success_msg)
        return super().form_valid(form)


class FeatureRequestUpdateView(SuccessMessageMixin, UpdateView):
    model = FeatureRequest
    form_class = FeatureRequestForm
    #fields = '__all__'
    success_message = "Feature Request updated!"
    context_object_name = 'feature_request'
    template_name = 'featurereq/featurerequest_update.html'


class FeatureRequestDetailView(DetailView):
    model = FeatureRequest
    form_class = FeatureRequestForm
    context_object_name = 'feature_request'
    template_name = 'featurereq/featurerequest_detail.html'



class FeatureRequestListView(ListView):
    model = FeatureRequest
    slug_field = 'title'
    slug_url_kwarg = 'title'
    context_object_name = 'feature_requests'
    template_name = 'featurereq/featurerequest_list.html'
    success_url = reverse_lazy('featurereq:index')



class FeatureRequestDeleteView(DeleteView):
    model = FeatureRequest
    template_name = 'featurereq/featurerequest_delete.html'
    context_object_name = 'feature_request'
    success_url = reverse_lazy('featurereq:index')

    def delete(self, request, *args, **kwargs):
        messages.success(self.request, 'Your feature request was deleted!')
        return super(FeatureRequestDeleteView, self).delete(request, *args, **kwargs)

mybritesite/featurereq/templates/base.html
{% load static %}

<html>
    <head>
        <title>Requests</title>
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
        <link href='//fonts.googleapis.com/css?family=Consolas&subset=latin,latin-ext' rel='stylesheet' type='text/css'>
        <link rel="stylesheet" href="{% static 'featurereq/style.css' %}">
    </head>
    <body>
    <div class="page-header">
        <h1><a href="/">Feature Requests</a></h1>
    </div>
    <div class="content container">
        <div class="row">
            <div class="col-md-8">
            {% block content %}
            {% endblock %}
            </div>
        </div>
    </div>
</body>
</html>

mybritesite/featurereq/templates/featurereq/featurerequest_create.html
{% extends "base.html" %}

{% load bootstrap3 %}

{% block title %}Create New Feature Request{% endblock %}

{% block content %}
  <div class="container">
    <div class="row">
      <div class="col-md-8 col-md-offset-2">
        <ol class="breadcrumb">
          <li><a href="/">Feature Requests</a></li>
          <li class="active">Submit Feature Request</li>
        </ol>

        <div class="page-header">
          <h1>Submit a Feature Request</h1>
        </div>

        {% bootstrap_form_errors form %}

        <form method="post" action="" class="form">
          {% bootstrap_form form %}
          {% csrf_token %}

          {% bootstrap_button "Submit" button_type="submit" button_class="btn-primary" %}
        </form>
      </div>
    </div>
  </div>
{% endblock %}

mybritesite/featurereq/templates/featurereq/featurerequest_delete.html
{% extends 'base.html' %}

{% load bootstrap3 %}

{% block title %}Delete Feature Request{% endblock %}

{% block content %}
  <div class="container">
    <div class="row">
      <div class="col-md-8 col-md-offset-2">
        <ol class="breadcrumb">
          <li><a href="/">Feature Requests</a></li>
          <li><a href="{% url 'featurereq:detail' feature_request.pk %}">{{ feature_request.title }}</a></li>

          <li class="active">Delete</li>
        </ol>

        <div class="page-header">
          <h1>Delete Feature Request</h1>
        </div>

        <p>
          Are you sure you would like to delete the feature request <strong>"{{ feature_request.title }}"</strong>?
        </p>

        <form method="post" action="" class="form">
          {% csrf_token %}
          {% bootstrap_button "Delete" button_type="submit" button_class="btn-danger" %}
        </form>
      </div>
    </div>
  </div>
{% endblock %}

mybritesite/featurereq/templates/featurereq/featurerequest_detail.html
{% extends 'base.html' %}

{% load bootstrap3 %}

{% block title %}{{ feature_request }}{% endblock %}
{% debug %}
{% block content %}
  <div class="container">
    <div class="row">
      <div class="col-md-8 col-md-offset-2">
        <ol class="breadcrumb">
          <li><a href="/">Feature Requests</a></li>
          <li class="active">{{ feature_request }}</li>
        </ol>

        <div class="page-header">
          <h1>{{ feature_request.title }}</h1>
        </div>

        <div>
          <dl class="dl-horizontal">
            {% if feature_request.description %}
              <dt>Description:</dt>
              <dd>{{ feature_request.description }}</dd>
            {% endif %}
            {% if feature_request.client %}
              <dt>Client:</dt>
              <dd>{{ feature_request.client }}</dd>
            {% endif %}
            {% if feature_request.client_priority %}
              <dt>Client Priority:</dt>
              <dd>{{ feature_request.client_priority }}</dd>
            {% endif %}
            {% if feature_request.product_area %}
              <dt>Product Area:</dt>
              <dd>{{ feature_request.product_area }}</dd>
            {% endif %}
            {% if feature_request.target_date %}
              <dt>Target Date:</dt>
              <dd>{{ feature_request.target_date }}</dd>
            {% endif %}

          </dl>
        </div>
        <div class="text-center">
          <a href="{% url 'featurereq:update' feature_request.pk %}" class="btn btn-default">{% bootstrap_icon 'edit' %} Update</a>
          <a href="{% url 'featurereq:delete' feature_request.pk %}" class="btn btn-danger">{% bootstrap_icon 'trash' %} Delete</a>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

mybritesite/featurereq/templates/featurereq/featurerequest_list.html
{% extends "base.html" %}

{% load bootstrap3 %}

{% block title %}New Feature Request added{% endblock %}

{% block content %}
  <div class="container">
    <div class="row">
      <div class="col-md-8 col-md-offset-2">
        <div class="page-header">
          <h1>Feature Requests</h1>
        </div>
        {% bootstrap_messages %}
        <div class="table-responsive">
          <table class="table table-striped">
            <thead>
              <tr>
                <th>Title</th>
                <th>Client</th>
                <th>Priority</th>
                <th>Product Area</th>
                <th>Target Date</th>
                <th></th>
              </tr>
            </thead>
            <tbody>
              {% for featurerequest in feature_requests %}
                <tr>
                  <td><a href="{% url 'featurereq:detail' featurerequest.pk %}">{{ featurerequest.title }}</a></td>
                  <td>{{ featurerequest.client }}</td>
                  <td>{{ featurerequest.client_priority }}</td>
                  <td>{{ featurerequest.product_area }}</td>
                  <td>{{ featurerequest.target_date }}</td>

                  <td>
                  </td>
                </tr>
              {% endfor %}
            </tbody>
          </table>
          <div class="text-center">
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

mybritesite/featurereq/templates/featurereq/featurerequest_update.html
{% extends "base.html" %}

{% load bootstrap3 %}

{% block title %}Update Feature Request{% endblock %}

{% block content %}
  <div class="container">
    <div class="row">
      <div class="col-md-8 col-md-offset-2">
        <ol class="breadcrumb">
          <li><a href="/">Feature Requests</a></li>
          <li class="active">Update</li>
        </ol>

        <div class="page-header">
          <h1>Update Feature Request</h1>
        </div>

        {% bootstrap_form_errors form %}

        <form method="post" action="" class="form">
          {% bootstrap_form form %}
          {% csrf_token %}

          {% bootstrap_button "Update" button_type="submit" button_class="btn-primary" %}
        </form>
      </div>
    </div>
  </div>
{% endblock %}

mybritesite/templates/home.html
{% extends "layout.html" %}

{% block title %}Well hello there!{% endblock %}

{% block content %}
<h1>Welcome!</h1>
{% endblock %}

mybritesite/templates/layout.html
{% load static from staticfiles %}

<html>
    <head>
        <title>{% block title %}{% endblock %}</title>
        <link rel="stylesheet" href="{% static 'css/layout.css' %}">

        {% block static %}{% endblock %}
    </head>
    <body>
        <div class="site-container">
                <a href="{% url 'featurerequest_list'%}">Projects</a>

        {% block content %}{% endblock %}
        </div>
    </body>
</html>